apiVersion: v1
kind: Service
metadata:
  name: headless-service-statfulset
  labels:
    app: nginx-sts-demo
spec:
  clusterIP: None
  selector:
    app: nginx-sts-demo
  ports:
  - port: 80
    name: web
