apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: 192.168.1.8 
    path: "/tmp/nfs/kubedata/pv0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: 192.168.1.8 
    path: "/tmp/nfs/kubedata/pv1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: 192.168.1.8 
    path: "/tmp/nfs/kubedata/pv2"